### ISSUE TITLE
Debug breakpoints are disabled

### ISSUE THREAD

**Issue by aharondavid** [nokotan/VSExtForEmscripten#9] opened 2022-03-03 09:30 UTC
Sub Project Module  is c++ compile to WebAssembly.
Main Project  is also c++, it use the above Module  and its output is html.
Didn't success to deubg the Module - breakpoints are disabled.

Here is the Debug Property of the WebAssembly Module:

![image](https://user-images.githubusercontent.com/41375082/156535298-5e1ca18b-2660-44b4-9dbe-30ffed75d378.png)

**Comment by nokotan** [comment] 2022-03-30 09:36
Does emrun.bat seem to be launched successfully? 
If the Command prompt with the message is shown, then it should be the debugger side problem.

The debugger works with the program that has a game loop and the program will not break until the debugger loads its all debugger symbols.

```bat
Web server root directory:
Now listening at http://0.0.0.0:6931/
```

**Comment by aharondavid** [comment] 2022-03-30 10:07
Hi,
I am glad to hear you :)

emrun.bat run successfully and I saw the result in the browser. 
my code do rendering in a loop. where ever I put a breakpoint, it is disabled:
![image](https://user-images.githubusercontent.com/41375082/160806840-d5638179-bff0-4a30-a255-52234e93c7ad.png)

**Comment by nokotan** [comment] 2022-03-30 13:29
Seems quite strange...
emrun is running properly, chrome is launched successfully, the project configuration is also correct.

Still I cannot reproduce this problem, please give me your emscripten version.

**Comment by nokotan** [comment] 2022-07-27 07:36
The debugger had ignored instrument breakpoints, that fires when WebAssembly files are parsed. And this had let code on a breakpoint executed before debug symbols were fully parsed.

This problem has been fixed in the current version and should be not reproducible.
If this issue still occurs, don't hesitate to re-open this issue.

**Closed as completed by nokotan** 2022-07-27 07:36 UTC

**Comment by aharondavid** [comment] 2022-07-27 13:04
Thanks a lot!

**Comment by aharondavid** [comment] 2022-09-25 07:30
Hi,
Still debugger doesn't attached - break point disabled.
* I noticed that the Chrome  is lunched with Web Assembly flag turned off.
* Debugging throughout Chrome DevTools  is work to me.
* Is there any additional flags that I should Turn On ?
