### ISSUE TITLE
visual studio 2022 17.11.0 not working

### ISSUE THREAD

**Issue by 120910383** [nokotan/VSExtForEmscripten#34] opened 2024-08-17 03:13 UTC
**Describe the bug**
1>------ Build started: Project: myemcc, Configuration: Debug Emscripten ------
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Platforms\Emscripten\PlatformToolsets\emcc\Toolset.targets(119,5): error MSB4062: The "EmscriptenCompile" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Platforms\Emscripten\PlatformToolsets\emcc\..\..\Emscripten.Build.CppTasks.dll. Could not load file or assembly 'Microsoft.Build.CPPTasks.Common, Version=17.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。 Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>Done building project "myemcc.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**

1. open windows11 sandbox
2. install visual studio 2022 17.11.0
3. only select c++ core desktop without any addition selection
4. visual studio => Extensions => Installed => Emscripten Extension Pack for Visual Studio 0.7.0
5. reopen
6. create emscripten project
7. run WebAssembly Debugger
8. error

**Expected behavior**

**Screenshots**

**Develop environment (please complete the following information):**
 - OS:  windows 11 23H2
 - Visual Studio version: VS2022 professional 17.11.0

**Additional context**

**Comment by Reputeless** [comment] 2024-08-27 15:05
おそらく同様の問題で、Visual Studio 2022 17.11 から 17.10.5 へのロールバックでエラーを回避できた事例が報告されました。

- https://x.com/aoroaoro/status/1828442383274648036?t=JmeMK0_PBWu6EPX4qbZ8mA&s=19

**Comment by nokotan** [comment] 2024-08-30 13:01
Hi, [120910383](https://github.com/120910383) and [Reputeless](https://github.com/Reputeless).

We doe's not have a good solution for this problem, as mentioned in the [D Language Visual Studio Extension issues](https://github.com/dlang/visuald/issues?q=is%3Aissue+dependencies).

This problem seems to be caused by "assembly binding redirection", this is specific behavior of the .Net Framework.
In this case, "Emscripten.Build.CppTasks.dll" requires "Microsoft.Build.CPPTasks.Common version 17.10.0.0" with complete assembly version match.

If you have good articles for this, please let me know.

**Comment by Reputeless** [comment] 2024-08-30 13:14
This error occurs in VSExtForEmscripten v0.9.0 but not in v0.8.0.
Tested on Visual Studio 2022 (17.11 and 17.12 Preview).

**Comment by nokotan** [comment] 2024-08-30 16:00
I've compared 2 vsix binaries, version 0.8.0 and version v0.9.0. 
It is found that version 0.8.0 includes the assembly file "Microsoft.Build.CPPTasks.Common.dll", but that version 0.9.0 does not.

Including "Microsoft.Build.CPPTasks.Common.dll" in a vsix binary was not intended because this assembly file is the private assembly of Visual Studio product. That means that we should not redistribute this file without permission.
Re-including this private assembly with the vsix binary will be the last option, asking Microsoft for the lisence.

I'm still looking for any tips on "assembly binding redirection" with MSBuild, or other good solution.

**Comment by ui0ppk** [comment] 2024-09-07 18:41
exact same issue

**Comment by nokotan** [comment] 2024-09-10 17:08
Here is the artifact file that is produced file on [GitHub workflows](https://github.com/nokotan/VSExtForEmscripten/actions/runs/10790307656).
Please try this vsix file and check if the problem is resolved. (Before installation, uninstall older version of this vsix if exists)
[VSExt-Build.Definition.vs2022.zip](https://github.com/user-attachments/files/16948337/VSExt-Build.Definition.vs2022.zip)

**Comment by 120910383** [comment] 2024-09-12 06:16
> Here is the artifact file that is produced file on [GitHub workflows](https://github.com/nokotan/VSExtForEmscripten/actions/runs/10790307656). Please try this vsix file and check if the problem is resolved. (Before installation, uninstall older version of this vsix if exists) [VSExt-Build.Definition.vs2022.zip](https://github.com/user-attachments/files/16948337/VSExt-Build.Definition.vs2022.zip)

after uninstall older version and install this, it works, really appreciate it, thank you

**Comment by nokotan** [comment] 2024-09-13 04:23
Thanks for trying this vsix file.

Closing this issue as v0.10.0 is released.

**Closed as completed by nokotan** 2024-09-13 04:23 UTC
